### PR TITLE
refactor: refactoring example to using Kratos SelfService UI Node Docker image

### PR DESCRIPTION
**Pull request by Jorgagu**
## Related Issue or Design Document
Refactoring example now Kratos SelfService UI Node is updated with the implementation of Hydra Consent screen.
PR of Kratos SeftService UI Node containing the code used previously in the example: https://github.com/ory/kratos-selfservice-ui-node/pull/257

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by Jorgagu** [comment]
@aeneasr @vinckr can you review this ?

**Comment by vinckr** [comment]
Hey @Jorgagu 
Apologies missed this, will review - thanks for the contribution!

**Comment by Jorgagu** [comment]
:wave: @vinckr any update or review on this PR ?

**Review by vinckr — APPROVED** [review]
This looks great, thanks so much @Jorgagu  🙌 

I ran the example and everything worked as expected, also many thanks for the clean up. 
This is an excellent basis for Hydra+Kratos integration and will see to promote it a bit more in the coming weeks.

**Pull request merged**
