### PR TITLE
feat: Hydra+NextJS TypeScript reference implementation

### PR DESCRIPTION
**Pull request by amorey**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
      vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
      maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by vinckr** [comment]
Hello @amorey 
apologies for the very late response here.
Is this a duplicate of https://github.com/ory/examples/pull/43 ?

**Comment by amorey** [comment]
#43 is for javascript, #44 is for typescript

**Comment by rworkduo** [comment]
any reason why this example is not approved after almost 2 years? it looks useful to vast nextjs community that uses typescript

**Comment by vinckr** [comment]
@rworkduo no good reason. I mostly have not tried it out! 
will merge now :-) 
thanks for the reminder

**Review by vinckr — APPROVED** [review]

**Comment by amorey** [comment]
Thanks for the merge!

**Pull request merged**
