### PR TITLE
feat: small fixes for supabase cloud blog post

### PR DESCRIPTION
**Pull request by gen1us2k**

### CODE REVIEW

**Review by vinckr — COMMENTED** [review]
I haven't tested it now, but LGTM! 

we should maybe think about how we can add testing to these examples soon 🤔

**Review by vinckr — DISMISSED** [review]

**Review by vinckr — APPROVED** [review]

**Comment by aeneasr** [comment]
@vinckr please test the code before you merge it. If it doesn't work and we could have caught that during testing, at least 10 people will struggle with this before bringing it to our attention.

**Comment by vinckr** [comment]
true, I made a note to test this example again. 
We really need some automated [testing](https://github.com/ory/examples/issues/8) though in the near future. Is playwright & jest what we use in the docs a good option here @aeneasr ?

**Comment by aeneasr** [comment]
Yes, I don't think you'll need jest - playwright is enough

**Pull request merged**
